### ISSUE TITLE
HW selection

### ISSUE THREAD

**Issue by teemupa** [nemonanja/furry-ironman#3]
Select hardware for the project

**Comment by teemupa** [comment]
IR thermometer, pressure sensor, LPC1768 + application board & WiFi wanted

**Comment by jonikula** [comment]
http://developer.mbed.org/components/Roving-Networks-WiFly-RN-171-XV/
http://developer.mbed.org/components/mbed-Application-Board/
http://developer.mbed.org/components/MLX90614-I2C-Infrared-Thermometer/ (https://www.sparkfun.com/products/9570)
Jumper wires to help connect the thermometer (example can be seen in the link above)
http://developer.mbed.org/platforms/mbed-LPC1768/

These are the ones available in mbed.org. Still need to find a mass sensor

**Comment by jonikula** [comment]
https://www.sparkfun.com/products/11207
This should do for the mass sensor. Integration into circuit needs a ~1MOhm resistor but I think I have some extras lying around somewhere. A breadboard would be nice to help with constructing the circuit and testing it before building a more "permanent" solution. I have all the solder materials etc. we're going to need.

**Comment by jonikula** [comment]
We should propably close this.
